apiVersion: batch/v1
kind: Job
metadata:
  name: phi-3-text2sql-k8s-job
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: ghcr.io/kyryl-opens-ml/gpu-jobs-comparison:latest
          name: training
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gpu-job-secrets
                  key: HF_TOKEN
            - name: WANDB_PROJECT
              value: gpu-jobs-comparison
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gpu-job-secrets
                  key: WANDB_API_KEY
            - name: RUN_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["python"]
          args: ["text2sql_training.py"]
          resources:
            limits:
              nvidia.com/gpu: 1