apiVersion: v1
kind: Pod
metadata:
  name: text2sql-training
spec:
  containers:
    - image: ghcr.io/kyryl-opens-ml/gpu-jobs-comparison:pr-1
      name: text2sql-training
      env:
        - name: HF_TOKEN
          value: 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
        - name: WANDB_PROJECT
          value: gpu-jobs-comparison
        - name: WANDB_API_KEY
          value: cb86168a2e8db7edb905da69307450f5e7867d66
        - name: RUN_NAME
          value: phi-3-mini-lora-text2sql-k8s-pod
      command: ["python"]
      args: ["text2sql_training.py"]
  restartPolicy: Never